import Head from "next/head";
import dbConnect from "../lib/dbConnect";
import Movie from "../models/Movie";
import Link from "next/link";

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="text-center">Movies</h1>

        <Link href={"/new"}>
          <a className="btn btn-primary w-100 mb-2">
            Agregar
          </a>
        </Link>

        <h1>
          {movies.map(({ title, _id, plot }) => (
            <div className="card mb-2" key={_id}>
              <div className="card-body">
                <p className="text-uppercase h5">{title}</p>
                <p className="fw-light">{plot}</p>
                <div>
                  <Link href="/[id]/edit" as={`/${_id}/edit`}>
                    <a className="btn btn-warning me-2">Editar</a>
                  </Link>
                  <Link href="/[id]" as={`/${_id}`}>
                    <a className="btn btn-info">Visualizar</a>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </h1>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect();
    const result = await Movie.find({});
    const movies = result.map((doc) => {
      const movie = doc.toObject();
      movie._id = movie._id.toString();
      return movie;
    });
    return { props: { movies } };
  } catch (error) {
    console.log(error);
  }
}
